---

info:
  description: Training configuration repo

spring:
  profiles: cloud

eureka:
  client:
    serviceUrl:
      defaultZone: https://timandgerard:herpderp@servicereg-unspontaneous-strikeover.cfapps.io/eureka
  instance:
    hostname: servicereg-unspontaneous-strikeover.cfapps.io
    nonSecurePort: 80